// GET ALL PRODUCT

export const GET_ALL_PRODUCT_REQUEST = "GET_ALL_PRODUCT_REQUEST"
export const GET_ALL_PRODUCT_SUCESS = "GET_ALL_PRODUCT_SUCESS"
export const GET_ALL_PRODUCT_FAIL = "GET_ALL_PRODUCT_FAIL"