// GET ALL PRODUCT

export const GET_ALL_PRODUCT_REQUEST = "GET_ALL_PRODUCT_REQUEST"
export const GET_ALL_PRODUCT_SUCESS = "GET_ALL_PRODUCT_SUCESS"
export const GET_ALL_PRODUCT_FAIL = "GET_ALL_PRODUCT_FAIL"

//GET SINGLE PRODUCT

export const GET_SINGLE_PRODUCT_REQUEST = "GET_SINGLE_PRODUCT_REQUEST"
export const GET_SINGLE_PRODUCT_SUCESS = "GET_SINGLE_PRODUCT_SUCESS"
export const GET_SINGLE_PRODUCT_FAIL = "GET_SINGLE_PRODUCT_FAIL"

// ADD TO CART

export const ADDTOCART_PRODUCT_REQUEST = "ADDTOCART_PRODUCT_REQUEST"
export const ADDTOCART_PRODUCT_SUCESS = "ADDTOCART_PRODUCT_SUCESS"
export const ADDTOCART_PRODUCT_FAIL = "ADDTOCART_PRODUCT_FAIL"


// GET FROM CART

export const GETFROMCART_PRODUCT_REQUEST = "GETFROMCART_PRODUCT_REQUEST"
export const GETFROMCART_PRODUCT_SUCESS = "GETFROMCART_PRODUCT_SUCESS"
export const GETFROMCART_PRODUCT_FAIL = "GETFROMCART_PRODUCT_FAIL"

// UPDATE CART

export const UPDATEFROMCART_PRODUCT_REQUEST = "UPDATEFROMCART_PRODUCT_REQUEST"
export const UPDATEFROMCART_PRODUCT_SUCESS = "UPDATEFROMCART_PRODUCT_SUCESS"
export const UPDATEFROMCART_PRODUCT_FAIL = "UPDATEFROMCART_PRODUCT_FAIL"

// DETETE FROM CART 

export const DELETEFROMCART_PRODUCT_REQUEST = "DELETEFROMCART_PRODUCT_REQUEST"
export const DELETEFROMCART_PRODUCT_SUCESS = "DELETEFROMCART_PRODUCT_SUCESS"
export const DELETEFROMCART_PRODUCT_FAIL = "DELETEFROMCART_PRODUCT_FAIL"