// LOGIN 
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCESS = "LOGIN_SUCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"


// SIGNUP

export const SIGNUP_REQUEST = "SIGNUP_REQUEST"
export const SIGNUP_SUCESS = "SIGNUP_SUCESS"
export const SIGNUP_FAIL = "SIGNUP_FAIL"

// ADMIN LOGIN

export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST"
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS"
export const ADMIN_LOGIN_FAILURE = "ADMIN_LOGIN_FAILURE"

// ADMIN SIGNIN

export const ADMIN_SIGNUP_REQUEST = "ADMIN_SIGNUP_REQUEST"
export const ADMIN_SIGNUP_SUCCESS = "ADMIN_SIGNUP_SUCCESS"
export const ADMIN_SIGNUP_FAILURE = "ADMIN_SIGNUP_FAILURE"


//  FORGET PASS

export const USER_FORGET_PASS_FIND_ACCOUNT_BY_EMAIL_REQUEST = "USER_FORGET_PASS_FIND_ACCOUNT_BY_EMAIL_REQUEST"
export const USER_FORGET_PASS_FIND_ACCOUNT_BY_EMAIL_SUCCESS = "USER_FORGET_PASS_FIND_ACCOUNT_BY_EMAIL_SUCCESS"
export const USER_FORGET_PASS_FIND_ACCOUNT_BY_EMAIL_FAIL = "USER_FORGET_PASS_FIND_ACCOUNT_BY_EMAIL_FAIL"

// CONFIRM PASS

export const USER_CONFIRM_PASS_FIND_ACCOUNT_BY_EMAIL_REQUEST = "USER_CONFIRM_PASS_FIND_ACCOUNT_BY_EMAIL_REQUEST"
export const USER_CONFIRM_PASS_FIND_ACCOUNT_BY_EMAIL_SUCCESS = "USER_CONFIRM_PASS_FIND_ACCOUNT_BY_EMAIL_SUCCESS"
export const USER_CONFIRM_PASS_FIND_ACCOUNT_BY_EMAIL_FAIL = "USER_CONFIRM_PASS_FIND_ACCOUNT_BY_EMAIL_FAIL"